application: kinoplayerapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  upload: app/index.html
  secure: always
  static_files: app/index.html

- url: .*
  static_dir: app